package.json, pnpm-lock.yaml, src/_providers/amplitude-provider.tsx, src/app/layout.tsx, src/shared/lib/amplitude.ts
> #15 amplitude 세팅
- amplitude 세팅
- 일단 트래킹 데이터에 어떤 데이터가 들어가게될지는 알 수 없어서 any 타입으로 지정해두었어요. (user_id 등)
- 추후 전역 상태로 로그인 데이터를 관리하게 되면 불러다가 그룹화해서 eventProperties는 매번 작성하지 않아도 되도록 수정가능 할 것 같아요.
- 단순히 유틸 함수를 통한 그룹화(eventProperties에 userid, device 등)가 아닌 context를 이용하는 방식도 있는데, context의 필요성을 못느끼겠어서 배제할 생각인데 의견주세요.
- 리플레이는 유료라 제외했습니다.
- 사용은 단순히 아래처럼 하면 됩니다. (당장은 any 타입이라 원하는 대로 삽입이 가능합니다.)
```javascript
import { trackEvent } from "@/src/shared/lib/amplitude";
...
function handleSearch(input: string) {
trackEvent("홈 검색 시도", { keyword: input });
...
}
```
=> feat: amplitude 세팅

src/entities/home/ui/home-body.tsx, src/entities/home/ui/home-header.tsx, src/entities/home/ui/home-keyword-list.tsx, src/entities/home/ui/scroll-item.tsx, src/entities/home/ui/scroll-section.tsx, src/features/home/ui/home-search.tsx, src/features/home/ui/navigate-clublist.tsx, src/shared/ui/Footer.tsx, src/shared/ui/button.tsx, src/views/home/home-page.tsx
[#44 ] 반응형 웹 적용
- [1] 07.29: 메인 페이지
- [2] 07.29: 푸터
[1] 메인 페이지 [2] 푸터
=> feat: 서비스 전체 responsive UI 적용

src/app/(main)/my/page.tsx
=> feat: 1차 배포 시도 (2차)

src/app/globals.css, src/entities/home/ui/category-text-card.tsx, src/entities/home/ui/comment-text-card.tsx, src/entities/recruit-detail/ui/review-star.tsx, src/widgets/home/ui/club-card-widget.tsx, src/widgets/home/ui/feature-intoduce-widget.tsx, src/widgets/home/ui/help-card-widget.tsx
[#75 ] fix: 헤더 index&코멘트 src 경로 이슈
>
=> fix: 헤더 index&코멘트 src 경로 이슈

route.ts, src/entities/club/ui/club-header.tsx, src/views/recruit/model/type.ts, src/views/recruit/ui/recruit-detail-page.tsx
=> [no-issue] fix: 라우팅 버그 수정

src/app/(main)/post-recruitment/[id]/layout.tsx, src/features/post-recruitment/ui/select-date.tsx, src/widgets/club-register/ui/club-edit-widget.tsx, src/widgets/club-register/ui/club-register-widget.tsx, src/widgets/post-recruitment/post-recruitment-widget.tsx
[#90] feat: 동아리 등록&모집 공고 등록 반응형 디자인
feat: 동아리 등록&모집 공고 등록 반응형 디자인
>
=> feat: 동아리 등록&모집 공고 등록 반응형 디자인

src/features/search/ui/search-input.tsx, src/views/home/ui/home-page.tsx, src/widgets/search/ui/search-results.tsx
[#88] feat: 검색 결과 페이지 반응형 디자인
검색 결과 페이지 반응형 디자인
>
=> feat: 검색 결과 페이지 반응형 디자인

src/auth.ts
=> fix: 쿠키 설정 변경

src/auth.ts, src/shared/api/auth-api.ts
=> [no-issue] fix: authApi 수정

src/entities/home/ui/home-keyword-list.tsx, src/entities/login/ui/login-header.tsx, src/shared/model/type.ts, src/shared/ui/category-nav-button.tsx, src/stories/molecules/club-search-item.stories.tsx, src/widgets/recruit/api/getClubList.ts, src/widgets/search/api/searchClubs.ts, src/widgets/search/ui/search-results.tsx
Fix: 로그인 문구 수정 및 홈 버튼 카테고리 수정
1. 로그인 문구 수정
2. 카테고리 수정
=> Fix: 로그인 문구 수정 및 홈 버튼 카테고리 수정

src/app/types/next-auth.d.ts, src/entities/login/ui/login-header.tsx
=> [no-issue] fix: build 오류 해결

public/robots.txt, public/sitemap.xml, src/app/(main)/club/[id]/layout.tsx, src/app/(main)/club/layout.tsx, src/app/(main)/favorite/layout.tsx, src/app/(main)/my/layout.tsx, src/app/(main)/recruit/[id]/layout.tsx, src/app/(main)/recruit/layout.tsx, src/app/(main)/support/layout.tsx, src/app/layout.tsx
feat: open graph 메타 설정 및 robot.txt 설정
>
=> feat: open graph 메타 설정 및 robot.txt 설정

src/entities/recruit-detail/ui/recruit-detail-header.tsx, src/entities/recruit-detail/ui/recruit-detail-view.tsx, src/entities/recruit-detail/util/convetLinkText.ts, src/features/header/ui/header-login.tsx, src/views/club/ui/club-detail-page.tsx, src/widgets/recruit-detail/ui/recruit-detail-widget.tsx, src/widgets/recruit/api/getClubList.ts, src/widgets/recruit/api/getClubRecruitList.ts
=> [no-issue] fix: ui 수정

src/entities/recruit/lib/getDateUtil.ts, src/features/post-recruitment/ui/select-date.tsx
[#148] 모집 기간 초 단위 등록
모집 기간 초 단위 등록
>
=> feat: 모집 기간 초 단위 등록

src/_providers/clarity-provider.tsx, src/app/(main)/layout.tsx
=> [no-issue] fix: clarity 설정

src/app/(main)/club-register/loading.tsx, src/app/(main)/favorite/page.tsx, src/entities/club/ui/club-header.tsx, src/shared/ui/club-item-skeleton.tsx, src/shared/ui/club-search-item-skeleton.tsx, src/shared/ui/favorite-list-skeleton-loading.tsx, src/shared/ui/item-list-skeleton-loading.tsx, src/shared/ui/search-list-skeleton-loading.tsx, src/views/club/ui/club-page.tsx, src/views/favorite/ui/favorite-page.tsx, src/views/home/ui/home-page.tsx, src/views/recruit/ui/recruit-page.tsx, src/views/search/ui/search-page.tsx, tsconfig.json
feat: 스켈레톤 ui 추가
1. 로딩 추가
2. 스켈레톤 ui 추가
>
=> feat: 스켈레톤 ui 추가

src/app/(main)/club-register/loading.tsx, src/shared/api/manage-api.ts, src/shared/ui/Footer.tsx, src/shared/ui/Header.tsx, src/views/club-register/ui/club-edit-page.tsx, src/views/post-recruitment/post-recruitment-page.tsx, src/widgets/club-register/ui/club-edit-widget.tsx, src/widgets/club-register/ui/club-register-widget.tsx, src/widgets/post-recruitment/post-recruitment-widget.tsx
=> [no-issue] fix: 동아리 권한 버그 수정

.github/workflows/auto-issue-labeler.yml
=> [no-issue] fix: 수정

.github/workflows/auto-issue-labeler.yml
=> [no-issue] fix: 라벨링 수정

.github/workflows/deploy.yml
[#226 ] feat: cicd deploy.yml 추가
>
=> feat: cicd deploy.yml 추가

.github/workflows/deploy.yml
chore: setting test
1. develop main 분기 처리
>
=> chore: setting test

.github/workflows/deploy.yml
=> [no-issue] chore: ci 수정 중복 제거

.github/workflows/deploy.yml
=> [no-issue] chore: deploay 수정3

.github/workflows/dev-server.yml
=> [no-issue] chore: deploay2

.github/workflows/deploy.yml
=> [no-issue] chore: deploay4

.github/workflows/deploy.yml
=> [no-issue] chore: prod 수정

.github/workflows/deploy.yml
=> [no-issue] chore: 개발 환경 분리2

.github/workflows/deploy.yml, .github/workflows/dev-server.yml
=> [no-issue] fix: signOut 버그 수정

src/app/api/sentry-webhook/route.ts, src/entities/favorite/ui/favorite-list-skeleton-loading.tsx, src/entities/favorite/ui/format-navigation.tsx, src/entities/home/ui/comment-text-card.tsx, src/features/favorite/ui/custom-calendar.tsx, src/features/favorite/util/get-week-days.ts, src/features/home/ui/card-slider.tsx, src/shared/ui/pagination-skeleton.tsx, src/views/favorite/ui/favorite-page.tsx, src/widgets/favorite/ui/favorite-item-section.tsx
Fix: 즐겨찾기 페이지 css 최적화
1. 즐겨찾기 css 깨짐 현상 해결
2. 즐겨찾기 반응형 매끄럽게 수정
=> Fix: 즐겨찾기 페이지 css 최적화
